# Generated by Django 5.1.3 on 2024-11-29 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_remove_subscription_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklymealplan',
            options={},
        ),
        migrations.RemoveField(
            model_name='weeklymealplan',
            name='daily_plans',
        ),
        migrations.RemoveField(
            model_name='weeklymealplan',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='weeklymealplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DailyMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('breakfast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakfast_meals', to='recipes.recipe')),
                ('dinner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinner_meals', to='recipes.recipe')),
                ('lunch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lunch_meals', to='recipes.recipe')),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='recipes.weeklymealplan')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('weekly_plan', 'date')},
            },
        ),
    ]
